### ISSUE TITLE
ModuleNotFoundError: No module named 'myInfo'

### ISSUE THREAD

**Issue by MemZhr** [JahkRCode/JahkRShop#1]
ModuleNotFoundError: No module named 'myInfo'
i get this when i try to run

**Comment by JahkRCode** [comment]
That is reserved for personal information. Just remove reference to myInfo and replace with your own username and password. I recommend using a constants file so you aren't hardcoding in credentials.

**Comment by MemZhr** [comment]
> That is reserved for personal information. Just remove reference to myInfo and replace with your own username and password. I recommend using a constants file so you aren't hardcoding in credentials.

Thanks for the help but i never used python before ever and im kinda confused on which part i need to change
